apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  ports:
  # port を targetPort に Forward する
  - port: 8888
    protocol: TCP
    targetPort: 8888
  # リクエストは、selector にマッチするいずれかの Pod に転送される。(複数ある場合はランダムに選ばれる)
  selector:
    app: demo
  type: ClusterIP
