@startuml
left to right direction

object 入金情報
入金情報 : 入金日
入金情報 : 入金者名
入金情報 : 金額

object オーダー情報
オーダー情報 : オーダーID
オーダー情報 : オーダー日
オーダー情報 : 決済方法

object 出荷指示情報
出荷指示情報 : 出荷予定日
出荷指示情報 : 入荷待ちの有無

object 出荷情報
出荷情報 : 出荷番号
出荷情報 : 出荷予定日

object 送り先情報
送り先情報 : 送り先名
送り先情報 : 郵便番号
送り先情報 : 住所
送り先情報 : 電話番号

object オーダー商品
オーダー商品 : 数量

object パッケージ
パッケージ : 商品名
パッケージ : 荷姿
パッケージ : 商品カテゴリ
パッケージ : 単価

object 取引先
取引先 : 名前
取引先 : 締め日

object 商品
商品 : 発注単位
商品 : 追加発注禁止

入金情報 "0..1"- オーダー情報

オーダー情報 "1"--"1" 出荷指示情報
出荷指示情報 <.. 出荷情報

オーダー情報 "1"--"1" 出荷情報

オーダー情報 o--"1" 送り先情報
送り先情報 <.. 出荷情報

オーダー情報 *--"*" オーダー商品 : オーダー商品
オーダー商品 <.. 出荷情報

オーダー商品 --"1" パッケージ
パッケージ o-"*" パッケージ
パッケージ <|-- 商品

取引先 - 商品
@enduml
